#define asembler asm
#define przerwij break
#define przypadek case
#define znak char
#define stala const
#define kontynuuj continue
#define domyslnie default
#define rob do
#define podwojnyzmiennyprzecinek double
#define inaczej else
#define wyliczenie enum
#define zewnetrzna extern
#define zmiennyprzecinek float
#define dla for
#define idzdo goto
#define jezeli if
#define wlinii inline
#define calkowita int
#define dlugi long
#define rejestrowa register
#define zwroc return
#define krotki short
#define znakowy signed
#define rozmiar sizeof
#define statyczny static
#define struktura struct
#define przelacz switch
#define definiujtyp typedef
#define unia union
#define bezznakowy unsigned
#define pusty void
#define lotny volatile
#define dopoki while
#define glowna main
#define drukujs printf
#define odczytajs scanf
